import type { Gif } from "./types"

export const mockGifs: Gif[] = [
  {
    id: "1",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Funny", "Surprised", "Aki"],
    uploadedBy: "NollyFan",
    socialLink: "https://twitter.com/nollyfan",
    views: 0,
    likes: 0,
  },
  {
    id: "2",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Dancing", "Pawpaw", "Celebration"],
    uploadedBy: "MemeKing",
    views: 0,
    likes: 0,
  },
  {
    id: "3",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Funny", "Duo", "Aki", "Pawpaw"],
    uploadedBy: "ComedyLover",
    socialLink: "https://instagram.com/comedylover",
    views: 0,
    likes: 0,
  },
  {
    id: "4",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Wahala", "Trouble", "Funny"],
    uploadedBy: "WahalaWatcher",
    views: 0,
    likes: 0,
  },
  {
    id: "5",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Judging You", "Funny", "Reaction"],
    uploadedBy: "ReactionQueen",
    views: 0,
    likes: 0,
  },
  {
    id: "6",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Celebration", "Aki", "Dancing"],
    uploadedBy: "PrankMaster",
    views: 0,
    likes: 0,
  },
  {
    id: "7",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Angry", "Pawpaw", "Reaction"],
    uploadedBy: "AngryFace",
    views: 0,
    likes: 0,
  },
  {
    id: "8",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Confused", "Funny", "Reaction"],
    uploadedBy: "ConfusedSoul",
    views: 0,
    likes: 0,
  },
  {
    id: "9",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Funny", "Laughing", "Duo"],
    uploadedBy: "LaughTrack",
    views: 0,
    likes: 0,
  },
  {
    id: "10",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Serious", "Business", "Funny"],
    uploadedBy: "BusinessTime",
    views: 0,
    likes: 0,
  },
  {
    id: "11",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Shocked", "Reaction", "Funny"],
    uploadedBy: "ShockValue",
    views: 0,
    likes: 0,
  },
  {
    id: "12",
    title: "",
    url: "/placeholder.svg?height=400&width=400",
    tags: ["Duo", "Funny", "Mischief"],
    uploadedBy: "MischiefMaker",
    views: 0,
    likes: 0,
  },
]
